In [2]:
import requests
import pandas as pd

In [3]:
# Fetch the user data
res = requests.get('https://jsonplaceholder.typicode.com/users')
data = res.json()

In [4]:
# Create a DataFrame
df = pd.DataFrame(columns=['Name', 'Username', 'Email', 'Street', 'Suite', 'City', 'Zip Code', 'Geo Latitude', 'Geo Longitude'])

In [5]:
# Parse the user data
for idx, user in enumerate(data):
    address = user.get("address", {})
    geo = address.get("geo", {})
    
    df.loc[idx, 'Name'] = user.get("name")
    df.loc[idx, 'Username'] = user.get("username")
    df.loc[idx, 'Email'] = user.get("email")
    df.loc[idx, 'Street'] = address.get("street")
    df.loc[idx, 'Suite'] = address.get("suite")
    df.loc[idx, 'City'] = address.get("city")
    df.loc[idx, 'Zip Code'] = address.get("zipcode")
    df.loc[idx, 'Geo Latitude'] = geo.get("lat")
    df.loc[idx, 'Geo Longitude'] = geo.get("lng")
    
df

,Name,Username,Email,Street,Suite,City,Zip Code,Geo Latitude,Geo Longitude
0,Leanne Graham,Bret,Sincere@april.biz,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496
1,Ervin Howell,Antonette,Shanna@melissa.tv,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618
2,Clementine Bauch,Samantha,Nathan@yesenia.net,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653
3,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990
4,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342
5,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,Norberto Crossing,Apt. 950,South Christy,23505-1337,-71.4197,71.7478
6,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,Rex Trail,Suite 280,Howemouth,58804-1099,24.8918,21.8984
7,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,Ellsworth Summit,Suite 729,Aliyaview,45169,-14.3990,-120.7677
8,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,Dayna Park,Suite 449,Bartholomebury,76495-3109,24.6463,-168.8889
9,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,-38.2386,57.2232

In [6]:
# Save to CSV
df.to_csv('users_data.csv', index=False)